const DATA=(window.DATA_PARTS||[]).flat(); const MD=window.MD||[]; const SUMMARY=window.SUMMARY||{}; const MDSUM=window.MDSUM||{};
const fmt=n=>new Intl.NumberFormat('th-TH').format(n); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let state={status:'คงค้าง',search:'',groupBy:'aging',field:null,value:null};
function colorFor(k){if(k.includes('เลยกำหนด')||k.includes('> 12')||k==='คงค้าง')return '#dc2626';if(k.includes('ครบกำหนด')||k.includes('6–12')||k.includes('ตรวจสอบ'))return '#d97706';if(k.includes('เสร็จ')||k.includes('< 3'))return '#16a34a';if(k.includes('พัก'))return '#7c3aed';return '#2563eb'}
function counts(arr,key){const m={};arr.forEach(x=>{const k=x[key]||'ไม่ระบุ';m[k]=(m[k]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function barChart(el,entries,field){const mx=Math.max(1,...entries.map(x=>x[1]));el.innerHTML=entries.map(([k,v])=>`<div class="barrow" data-field="${field}" data-value="${esc(k)}"><div class="barlabel" title="${esc(k)}">${esc(k)}</div><div class="bartrack"><div class="bar" style="width:${v/mx*100}%;background:${colorFor(k)}"></div></div><div class="barval">${v}</div></div>`).join('')||'<div class="muted">ไม่มีข้อมูล</div>'; el.querySelectorAll('.barrow').forEach(r=>r.onclick=()=>{state.field=r.dataset.field;state.value=r.dataset.value;renderAll()})}
function donut(el,parts,center,sub){const total=parts.reduce((s,x)=>s+x[1],0)||1;let deg=0;const stops=[];parts.forEach(([k,v])=>{let nd=deg+v/total*360;stops.push(`${colorFor(k)} ${deg}deg ${nd}deg`);deg=nd});el.innerHTML=`<div class="donutwrap"><div class="donut" style="background:conic-gradient(${stops.join(',')})"><div class="donutcenter"><b>${center}</b><span class="muted">${sub}</span></div></div><div class="legend">${parts.map(([k,v])=>`<div><span class="dot" style="background:${colorFor(k)}"></span>${esc(k)} <b>${v}</b></div>`).join('')}</div></div>`}
function filtered(){let a=DATA.filter(x=>state.status==='ALL'||x.status===state.status);if(state.search){const q=state.search.toLowerCase();a=a.filter(x=>Object.values(x).some(v=>String(v??'').toLowerCase().includes(q)))}if(state.field&&state.value)a=a.filter(x=>(x[state.field]||'ไม่ระบุ')===state.value);return a}
function cards(){const total=SUMMARY.total,b=SUMMARY.backlog,c=SUMMARY.complete,u=SUMMARY.incompleteData; const old=(SUMMARY.aging['> 12 เดือน']||0)+(SUMMARY.aging['6–12 เดือน']||0); document.getElementById('cards').innerHTML=[['งานหลักทั้งหมด',total,'Parent-level'],['คงค้าง',b,(b/total*100).toFixed(1)+'% ของทั้งหมด'],['เสร็จ',c,(c/total*100).toFixed(1)+'% ของทั้งหมด'],['ค้าง > 6 เดือน',old,(old/b*100).toFixed(1)+'% ของ Backlog'],['ข้อมูลไม่ครบ',u,'ต้องเคลียร์ Source Data']].map((x,i)=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="foot">${x[2]}</div></div>`).join('')}
function itemHtml(x){return `<div class="item"><div class="item-head"><div>#${x.id}</div><div class="item-name">${esc(x.name)}</div><div>${esc(x.category)}</div><div>${esc(x.requester)}</div><div>${esc(x.planRaw||'-')}</div><div><span class="pill">${esc(x.dueStatus||x.status)}</span></div></div><details><summary>ดูรายละเอียดรายการ</summary><div class="detailbox"><div><b>วันที่รับ:</b> ${esc(x.receivedRaw||'-')}</div><div><b>Aging:</b> ${esc(x.aging||'-')} ${x.ageDays!=null?'('+x.ageDays+' วัน)':''}</div><div><b>ประเภทเดิม:</b> ${esc(x.categoryRaw||'-')}</div><div><b>ระดับความยาก:</b> ${esc(x.difficulty)}</div><div><b>Plan:</b> ${esc(x.planRaw||'-')}</div><div><b>Actual:</b> ${esc(x.actualRaw||'-')}</div><div><b>ผู้แจ้ง:</b> ${esc(x.requester)}</div><div><b>Excel Row:</b> ${x.excelRow}</div><div class="full"><b>รายละเอียด/สถานะ:</b> ${esc(x.detail||'-')}</div></div></details></div>`}
function drill(a){const key=state.groupBy;const groups={};a.forEach(x=>{const k=x[key]||'ไม่ระบุ';(groups[k]??=[]).push(x)});const entries=Object.entries(groups).sort((a,b)=>b[1].length-a[1].length);document.getElementById('drilldown').innerHTML=entries.map(([k,items])=>`<details class="group"><summary class="group-summary"><span class="chev"></span><b>${esc(k)}</b><b>${items.length} งาน</b><span>${(items.length/Math.max(a.length,1)*100).toFixed(1)}%</span><span class="muted">กด + เพื่อเปิดดูรายการจริง</span></summary><div class="group-list">${items.sort((a,b)=>(b.ageDays||-1)-(a.ageDays||-1)).map(itemHtml).join('')}</div></details>`).join('')||'<div class="panel muted">ไม่พบรายการตาม Filter</div>'}
function master(a){document.getElementById('masterBody').innerHTML=a.map(x=>`<tr><td>${x.id}</td><td><b>${esc(x.name)}</b><div class="muted">${esc((x.detail||'').slice(0,80))}</div></td><td>${esc(x.category)}</td><td>${esc(x.requester)}</td><td>${esc(x.receivedRaw||'-')}</td><td>${esc(x.aging||'-')}</td><td>${esc(x.planRaw||'-')}</td><td>${esc(x.dueStatus||'-')}</td><td>${esc(x.difficulty)}</td><td>${esc(x.status)}</td><td><button class="secondary small" onclick="this.closest('tr').nextElementSibling.classList.toggle('hidden')">รายละเอียด</button></td></tr><tr class="hidden"><td colspan="11"><div class="detailbox"><div><b>Excel row:</b> ${x.excelRow}</div><div><b>Actual:</b> ${esc(x.actualRaw||'-')}</div><div class="full"><b>รายละเอียด:</b> ${esc(x.detail||'-')}</div></div></td></tr>`).join('')}
function renderAll(){const a=filtered();document.getElementById('resultCount').textContent=`แสดง ${a.length} รายการ`;drill(a);master(a); const base=DATA.filter(x=>x.status==='คงค้าง'); barChart(document.getElementById('agingChart'),counts(base,'aging'),'aging');barChart(document.getElementById('categoryChart'),counts(base,'category').slice(0,12),'category');barChart(document.getElementById('dueChart'),counts(base,'dueStatus'),'dueStatus')}
function setupInsights(){const b=SUMMARY.backlog;const old=(SUMMARY.aging['> 12 เดือน']||0)+(SUMMARY.aging['6–12 เดือน']||0);const noTarget=(SUMMARY.due['ไม่มี Target Date']||0)+(SUMMARY.due['ตรวจสอบ Plan']||0);const top=Object.entries(SUMMARY.category).sort((a,b)=>b[1]-a[1])[0]||['-',0];document.getElementById('insights').innerHTML=`<div><b>Old Backlog:</b> ${old}/${b} งาน (${(old/b*100).toFixed(0)}%) มีอายุเกิน 6 เดือน</div><div><b>Planning Gap:</b> ${noTarget} งาน ไม่มี Target ที่ใช้ติดตามได้หรือ Plan ต้องตรวจสอบ</div><div><b>Concentration:</b> หมวด “${esc(top[0])}” สูงสุด ${top[1]} งาน</div>`}
function csvExport(){const a=filtered();const cols=[['No','id'],['งาน','name'],['หมวด','category'],['ผู้แจ้ง','requester'],['วันที่รับ','receivedRaw'],['Aging','aging'],['Plan','planRaw'],['Actual','actualRaw'],['Due Status','dueStatus'],['ความยาก','difficulty'],['Status','status'],['รายละเอียด','detail']];let s='﻿'+cols.map(c=>c[0]).join(',')+'\n';a.forEach(x=>s+=cols.map(c=>'"'+String(x[c[1]]??'').replaceAll('"','""')+'"').join(',')+'\n');const blob=new Blob([s],{type:'text/csv;charset=utf-8'});const u=URL.createObjectURL(blob);const A=document.createElement('a');A.href=u;A.download='building_backlog_filtered.csv';A.click();URL.revokeObjectURL(u)}
function initBuilding(){cards();donut(document.getElementById('statusDonut'),[['คงค้าง',SUMMARY.backlog],['เสร็จ',SUMMARY.complete],['ข้อมูลไม่ครบ',SUMMARY.incompleteData]],SUMMARY.total,'งานหลัก');setupInsights();renderAll();document.getElementById('search').oninput=e=>{state.search=e.target.value;renderAll()};document.getElementById('statusFilter').onchange=e=>{state.status=e.target.value;state.field=null;state.value=null;renderAll()};document.getElementById('groupBy').onchange=e=>{state.groupBy=e.target.value;renderAll()};document.getElementById('reset').onclick=()=>{state={status:'คงค้าง',search:'',groupBy:document.getElementById('groupBy').value,field:null,value:null};document.getElementById('search').value='';document.getElementById('statusFilter').value='คงค้าง';renderAll()};document.getElementById('csv').onclick=csvExport}
let mdState={status:'ALL',search:''};function mdFiltered(){let a=MD.filter(x=>mdState.status==='ALL'||x.status===mdState.status);if(mdState.search){const q=mdState.search.toLowerCase();a=a.filter(x=>Object.values(x).some(v=>String(v??'').toLowerCase().includes(q)))}return a}
function renderMD(){const a=mdFiltered();document.getElementById('mdCount').textContent=`แสดง ${a.length} รายการ`;document.getElementById('mdBody').innerHTML=a.map(x=>`<tr><td>${x.id}</td><td><b>${esc(x.name)}</b></td><td>${esc(x.receivedRaw||'-')}</td><td>${esc(x.targetRaw||'-')}</td><td>${esc(x.actualRaw||'-')}</td><td>${esc(x.dueStatus)}</td><td>${esc(x.status)}</td><td>${esc(x.note||'-')}</td></tr>`).join('')}
function initMD(){document.getElementById('mdCards').innerHTML=[['งานทั้งหมด',MDSUM.total,'ตาม Source'],['เสร็จ',MDSUM.complete,(MDSUM.complete/MDSUM.total*100).toFixed(1)+'%'],['คงค้าง',MDSUM.backlog,'ยังต้องติดตาม'],['พัก/ชะลอ',MDSUM.hold,'รอการตัดสินใจ/ดำเนินการ']].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="foot">${x[2]}</div></div>`).join('');donut(document.getElementById('mdDonut'),counts(MD,'status'),MDSUM.total,'งาน MD');barChart(document.getElementById('mdDueChart'),counts(MD.filter(x=>x.status!=='เสร็จ'),'dueStatus'),'dueStatus');renderMD();document.getElementById('mdSearch').oninput=e=>{mdState.search=e.target.value;renderMD()};document.getElementById('mdStatus').onchange=e=>{mdState.status=e.target.value;renderMD()};document.getElementById('mdReset').onclick=()=>{mdState={status:'ALL',search:''};document.getElementById('mdSearch').value='';document.getElementById('mdStatus').value='ALL';renderMD()}}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');const md=t.dataset.tab==='md';document.getElementById('buildingTab').classList.toggle('hidden',md);document.getElementById('mdTab').classList.toggle('hidden',!md)});
initBuilding();initMD();
